// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt02QB4brcpPk_Ik08lm2HkMotuIaYqbY',
    appId: '1:765844353524:web:836702cc4580ddf0f089a1',
    messagingSenderId: '765844353524',
    projectId: 'ai-face-regonition',
    authDomain: 'ai-face-regonition.firebaseapp.com',
    storageBucket: 'ai-face-regonition.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9Xvvw_1hnz7eruhKcMpmR2SXGBex_kDs',
    appId: '1:765844353524:android:acec90a1c6e324e8f089a1',
    messagingSenderId: '765844353524',
    projectId: 'ai-face-regonition',
    storageBucket: 'ai-face-regonition.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdH81-oZK9SSX-x6jPNqGX25b06YS47to',
    appId: '1:765844353524:ios:0d9cb4771a8e5188f089a1',
    messagingSenderId: '765844353524',
    projectId: 'ai-face-regonition',
    storageBucket: 'ai-face-regonition.firebasestorage.app',
    iosBundleId: 'com.example.faceAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdH81-oZK9SSX-x6jPNqGX25b06YS47to',
    appId: '1:765844353524:ios:0d9cb4771a8e5188f089a1',
    messagingSenderId: '765844353524',
    projectId: 'ai-face-regonition',
    storageBucket: 'ai-face-regonition.firebasestorage.app',
    iosBundleId: 'com.example.faceAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt02QB4brcpPk_Ik08lm2HkMotuIaYqbY',
    appId: '1:765844353524:web:3591c38fab5afec8f089a1',
    messagingSenderId: '765844353524',
    projectId: 'ai-face-regonition',
    authDomain: 'ai-face-regonition.firebaseapp.com',
    storageBucket: 'ai-face-regonition.firebasestorage.app',
  );
}